project:
  type: website
  output-dir: docs

website:
  title: "Sungsoo Park, DVM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: resume.qmd
        text: CV
    right:
      - icon: instagram
        href: https://www.instagram.com/sungspark0405
      - icon: github
        href: https://github.com/sungspark-lab
      - icon: envelope
        text: Email
        href: mailto:sungspark@o.cnu.ac.kr

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
